node('maven') {

     withMaven(maven:'mvn_home') {
 
    
        stage('Checkout') {
            git url: 'https://github.com/cdpdevops/newmsapp.git', credentialsId: 'gitaccess', branch: 'microbes'
        }

        stage('Build') {
            sh 'mvn -f discovery-service/pom.xml clean install'
            def pom = readMavenPom file:'discovery-service/pom.xml'
            print pom.version
            env.version = pom.version
        }
     }

        
node ('dockerhost') {

        stage ('Run') {
            docker.image("cdp-shreeapp:v0.1").run('-p 8761:8761 --name discovery')
        }

}