node ('maven') {

    withMaven(maven:'mvn_home') {

        stage('Checkout') {
            git url: 'https://github.com/cdpdevops/newmsapp.git', credentialsId: 'gitaccess', branch: 'microbes'
        }

        stage('Build') {
            sh 'mvn -f gateway-service/pom.xml clean install'

            def pom = readMavenPom file:'gateway-service/pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('gateway-service') {
                docker.withServer('tcp://10.0.1.15:2375'){
                def app = docker.build "cdp-gateway-service:${env.version}"
                }
            }
        }

        stage ('Run') {
            docker.withServer('tcp://10.0.1.15:2375'){
            docker.image("cdp-gateway-service:${env.version}").run('-p 8765:8765 --name gateway --link newaccount --link discovery')
            }
        }
     

    }

}