node ('maven') {

    withMaven(maven:'mvn_home') {

        stage('Checkout') {
            git url: 'https://github.com/cdpdevops/newmsapp.git', credentialsId: 'gitaccess', branch: 'microbes'
        }

        stage('Build') {
            sh 'mvn -f account-service/pom.xml clean install'

            def pom = readMavenPom file:'account-service/pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('account-service') {
                docker.withServer('tcp://10.0.1.15:2375'){
                def app = docker.build "cdp-account-service:${env.version}"
                }
            }
        }

        stage ('Run') {
            docker.withServer('tcp://10.0.1.15:2375'){
            docker.image("cdp-account-service:${env.version}").run('-p 2222:2222 --name account')
            }
        }
    }

}